# Generated by Django 2.2.2 on 2020-07-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200727_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='coursechapter',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='coursesection',
            old_name='update_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
