# Generated by Django 2.2.2 on 2020-07-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200727_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
